version: '3.3'
services:
  db:
    image: 'mysql:latest'
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_DATABASE: dbjavacourse
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      -  '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  my-db: