### CORS DEFINITION ###
cors:
  originPattenrs: http://localhost:3000,http://localhost:8080,http://monteiro.com.br
### SECURITY CONFIGURATION WITH JWT ###
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
### SERVER PORT DEFINITION ###
server:
  port: 9595
  #Para alterar a porta padrão da aplicação
spring:
### DATABASE DEFINITION ###
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  flyway:
    enable: true
    locations: classpath:/db/migration
spring-doc:
### SWAGGER-IU DEFINITION ###
  pathsToMatch: /api/**/v1/**
  swagger-iu:
    use-root-path: true