### CORS DEFINITION ###
cors:
  originPattenrs: http://db:3000,http://localhost:8080,http://monteiro.com.br
### FILE REPOSITORY ###
file:
  upload-dir: /uploadDir
### SECURITY CONFIGURATION WITH JWT ###
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
### SERVER PORT DEFINITION ###
server:
  port: 80
  #Para alterar a porta padrão da aplicação
spring:
### DATABASE DEFINITION ###
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  flyway:
    enable: true
    locations: classpath:/db/migration
spring-doc:
### SWAGGER-IU DEFINITION ###
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-iu:
    use-root-path: true